/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.oracleconnector;

/**
 *
 * @author eros
 */
public class StaticQuerys {


      public static String QUERY4EXAMEFORMATADO =
                                                            " SELECT"
 +"  0        AS TAB_FL_QTDECH,"
  +" 0             AS RTP_FL_VALORCH,"
  +" 0             AS RTP_FL_VALORCHEXTERNO,"
  +" 0             AS RTP_FL_DESCONTO,"
  +" 0             AS RTP_FL_DESCONTOEXTERNO,"
  +" 0             AS RTP_FL_ACRESCIMO,"
  +" EXD_ST_TABELA AS TAP_ST_CODIGO,"
  +" REG.REG_CH_OBRIGATORIONUMGUIA,"

  +" EXD_ST_CODIGO           AS TAB_ST_CODIGO,"
  +" ''                      AS TAP_ST_DESCRICAO,"
  +" EDI.EDI_FL_VALOR        AS ETP_FL_VALORDIFENCIADO,"
  +" EDI.EDI_FL_VALOREXTERNO AS ETP_FL_VALORDIFENCIADOEXTERNO,"
  +" EDI.EDI_FL_DESCONTO,"
  +" EDI.EDI_FL_DESCONTOEXTERNO,"
  +" (SELECT"
  +" CASE"
  +" WHEN COUNT(*) > 0"
  +" THEN 'S'"
  +" ELSE 'N'"
  +" END"
  +" FROM LAB_EXAMESCOMAUTORIZACAO"
  +" WHERE UNI_ST_CODIGO = EDI.UNI_ST_CODIGO"
  +" AND CON_ST_CODIGO   = EDI.CON_ST_CODIGO"
  +" AND REG_ST_CODIGO   = EDI.REG_ST_CODIGO"
  +" AND EXA_ST_CODIGO   = EDI.EXA_ST_CODIGO"
  +" ) AS ETP_ch_comautorizacao,"
  +" (SELECT"
  +" CASE"
  +" WHEN COUNT(*) > 0"
  +" THEN 'S'"
  +" ELSE 'N'"
  +" END"
  +" FROM LAB_EXAMENAOAUTORIZADOS"
  +" WHERE UNI_ST_CODIGO = EDI.UNI_ST_CODIGO"
  +" AND CON_ST_CODIGO   = EDI.CON_ST_CODIGO"
  +" AND REG_ST_CODIGO   = EDI.REG_ST_CODIGO"
  +" AND EXA_ST_CODIGO   = EDI.EXA_ST_CODIGO"
  +" ) AS ETP_ch_naoautorizado,"
  +" MAT.MAT_ST_CODIGO,"
  +" MAT.MAT_ST_DESCRICAO,"
  +" EXA.EXA_CH_OBRIGATORIOPESO,"
  +" EXA.EXA_CH_OBRIGATORIOALTURA,"
  +" EXA.EXA_CH_OBRIGAGESTANTE,"
  +" EXA.EXA_CH_SEXO,"
  +" EXU.MPA_ST_CODIGO,"
  +" EXA.EXA_ST_DESCRICAO,"
  +" EXA.EXA_CH_GRUPO,"
  +" EXU.MET_ST_CODIGO,"
  +" MET.MET_ST_DESCRICAO,"
  +" EXM.EXM_DT_VALIDADE,"
  +" EXU.EXU_CH_STATUS,"
  +" EXU.EXU_CH_FATURA,"
  +" EXA.EXA_CH_INATIVO,"
  +" EXU.EXU_CH_INATIVO,"
  +" EXU.EXU_CH_PREPARO,"
  +" EXU.EXU_CH_obrigamaterial,"
  +" EXU.PRA_ST_CODIGO,"
  +" PRA.PRA_IN_DIAS,"
  +" PRA.PRA_CH_DOMINGO,"
  +" PRA.PRA_CH_SEGUNDA,"
  +" PRA.PRA_CH_TERCA,"
  +" PRA.PRA_CH_QUARTA,"
  +" PRA.PRA_CH_QUINTA,"
  +" PRA.PRA_CH_SEXTA,"
  +" PRA.PRA_CH_SABADO,"
  +" PRA.PRA_HR_FINAL,"
  +" PRA.PRA_IN_HORAS    AS pra_in_horas,"
  +" PRA1.PRA_IN_HORAS   AS pra_in_horasU,"
  +" PRA1.PRA_IN_DIAS    AS pra_in_diasU,"
  +" PRA1.PRA_CH_SEGUNDA AS pra_ch_segundaU,"
  +" PRA1.PRA_CH_TERCA   AS pra_ch_tercaU,"
  +" PRA1.PRA_CH_QUARTA  AS pra_ch_quartaU,"
  +" PRA1.PRA_CH_QUINTA  AS pra_ch_quintaU,"
  +" PRA1.PRA_CH_SEXTA   AS pra_ch_sextaU,"
  +" PRA1.PRA_CH_SABADO  AS pra_ch_sabadoU,"
  +" PRA1.PRA_CH_DOMINGO AS pra_ch_domingoU,"
  +" PRA1.PRA_HR_FINAL   AS PRA_HR_FINALU,"
  +" EXU.EXU_ST_PRAZOURGENTE,"
  +" EXU.EXU_CH_NAONECESSARIO,"
  +" ORI.ORI_ST_CODIGO,"
  +" ORI.ORI_CH_URGENCIA,"
  +" ORI.LEG_ST_CODIGOINICIAL,"
  +" ORI.ORI_CH_CONFEREAUTOMATICO,"
  +" ORI.ORI_CH_CONFEREAUTOMATICOFAT,"
  +" EXU.SET_ST_CODIGO,"
  +" EXU.EXU_ST_UNIDADEEX,"
  +" EXU.EXU_ST_UNIDADEEXURGENTE,"
  +" EXU.EXU_CH_CONFEREAUTOMATICOFAT,"
  +" (SELECT MAX(EXA_ST_CODIGO)"
  +" FROM LAB_EXAMEDEPENDENTE"
  +" WHERE UNI_ST_CODIGO =?" //uniStCodigo  01
  +" AND EXA_ST_CODIGO   =?"//exaStCodigo   02
  +" ) AS DEP_ST_CODIGO"
  +" FROM LAB_EXAMESDIFERENCIADOS EDI,"
  +" LAB_REGRAS REG,"
  +" LAB_EXAMEUNIDADE EXU,"
  +" LAB_ORIGEM ORI,"
  +" LAB_PRAZO PRA1,"
  +" LAB_PRAZO PRA,"
  +" LAB_EXAME EXA,"
  +" LAB_EXAMEMETODO EXM,"
  +" LAB_METODO MET,"
  +" LAB_MATERIAL MAT"
  +" WHERE EDI.UNI_ST_CODIGO     = REG.UNI_ST_CODIGO"
  +" AND EDI.CON_ST_CODIGO       = REG.CON_ST_CODIGO"
  +" AND EDI.REG_ST_CODIGO       = REG.REG_ST_CODIGO"
  +" AND EDI.UNI_ST_CODIGO       = EXU.UNI_ST_CODIGO"
  +" AND EDI.EXA_ST_CODIGO       = EXU.EXA_ST_CODIGO"
  +" AND EDI.UNI_ST_CODIGO       = ORI.UNI_ST_CODIGO"
  +" AND EXU.EXA_ST_CODIGO       = EXA.EXA_ST_CODIGO"
  +" AND EXU.EXU_ST_PRAZOURGENTE = PRA1.PRA_ST_CODIGO(+)"
  +" AND EXU.PRA_ST_CODIGO       = PRA.PRA_ST_CODIGO(+)"
  +" AND EXU.EXA_ST_CODIGO       = EXM.EXA_ST_CODIGO(+)"
  +" AND EXU.MET_ST_CODIGO       = EXM.MET_ST_CODIGO(+)"
  +" AND EXU.MET_ST_CODIGO       = MET.MET_ST_CODIGO(+)"
  +" AND EXA.MAT_ST_COLETA       = MAT.MAT_ST_CODIGO(+)"
  +" AND EDI.UNI_ST_CODIGO       =?"//uniStCodigo 03
  +" AND ORI.ORI_ST_CODIGO       =?"//oriStCodigo 04
  +" AND EDI.CON_ST_CODIGO       =?"//conStCodigo 05
  +" AND EDI.REG_ST_CODIGO       =?"//regStCodigo 06
  +" AND EDI.EXA_ST_CODIGO       =?"//exaStCodigo 07
  +" AND EDI_DT_INICIOVALIDADE   ="
  +" (SELECT MAX(EDI_DT_INICIOVALIDADE)"
  +" FROM LAB_EXAMESDIFERENCIADOS"
  +" WHERE UNI_ST_CODIGO        =?"//uniStCodigo 08
  +" AND CON_ST_CODIGO          =?"//conStCodigo 09
  +" AND REG_ST_CODIGO          =?"//regStCodigo 10
  +" AND EXA_ST_CODIGO          =?"//exaStCodigo 11
  +" AND EDI_DT_INICIOVALIDADE <= TO_DATE(?,'YYYY-MM-DD')"//DATE 12
  +" )"

 +" UNION ALL"

+" SELECT TAB1.TAB_FL_QTDECH,"
  +" RTP1.rtp_fl_valorch,"
  +" RTP1.RTP_FL_VALORCHEXTERNO,"
  +" RTP1.rtp_fl_desconto,"
  +" RTP1.rtp_fl_descontoEXTERNO,"
  +" RTP1.rtp_fl_acrescimo,"
  +" RTP1.TAP_ST_CODIGO,"
  +" REG1.REG_CH_OBRIGATORIONUMGUIA,"
  +" TAB1.TAB_ST_CODIGO,"
  +" TAP1.tap_st_descricao,"
  +" 0 AS ETP_fl_valordifenciado,"
  +" 0 AS ETP_fl_valordifenciadoExterno,"
  +" 0 AS EDI_FL_DESCONTO,"
  +" 0 AS EDI_FL_DESCONTOEXTERNO,"
  +" (SELECT"
    +" CASE"
      +" WHEN COUNT(*) > 0"
      +" THEN 'S'"
      +" ELSE 'N'"
    +" END"
  +" FROM LAB_EXAMESCOMAUTORIZACAO"
  +" WHERE UNI_ST_CODIGO = RTP1.UNI_ST_CODIGO"
  +" AND CON_ST_CODIGO   = RTP1.CON_ST_CODIGO"
  +" AND REG_ST_CODIGO   = RTP1.REG_ST_CODIGO"
  +" AND EXA_ST_CODIGO   = ETP1.EXA_ST_CODIGO"
  +" ) AS ETP_ch_comautorizacao,"
  +" (SELECT"
    +" CASE"
      +" WHEN COUNT(*) > 0"
      +" THEN 'S'"
      +" ELSE 'N'"
    +" END"
  +" FROM LAB_EXAMENAOAUTORIZADOS"
  +" WHERE UNI_ST_CODIGO = RTP1.UNI_ST_CODIGO"
  +" AND CON_ST_CODIGO   = RTP1.CON_ST_CODIGO"
  +" AND REG_ST_CODIGO   = RTP1.REG_ST_CODIGO"
  +" AND EXA_ST_CODIGO   = ETP1.EXA_ST_CODIGO"
  +" ) AS ETP_ch_naoautorizado,"
  +" MAT.MAT_ST_CODIGO,"
  +" MAT.MAT_ST_DESCRICAO,"
  +" EXA.EXA_CH_OBRIGATORIOPESO,"
  +" EXA.EXA_CH_OBRIGATORIOALTURA,"
  +" EXA.EXA_CH_OBRIGAGESTANTE,"
  +" EXA.EXA_CH_SEXO,"
  +" EXU.MPA_ST_CODIGO,"
  +" EXA.EXA_ST_DESCRICAO,"
  +" EXA.EXA_CH_GRUPO,"
  +" EXU.MET_ST_CODIGO,"
  +" MET.MET_ST_DESCRICAO,"
  +" EXM.EXM_DT_VALIDADE,"
  +" EXU.EXU_CH_STATUS,"
  +" EXU.EXU_CH_FATURA,"
  +" EXA.EXA_CH_INATIVO,"
  +" EXU.EXU_CH_INATIVO,"
  +" EXU.EXU_CH_PREPARO,"
  +" EXU.EXU_CH_obrigamaterial,"
  +" EXU.PRA_ST_CODIGO,"
  +" PRA.PRA_IN_DIAS,"
  +" PRA.PRA_CH_DOMINGO,"
  +" PRA.PRA_CH_SEGUNDA,"
  +" PRA.PRA_CH_TERCA,"
  +" PRA.PRA_CH_QUARTA,"
  +" PRA.PRA_CH_QUINTA,"
  +" PRA.PRA_CH_SEXTA,"
  +" PRA.PRA_CH_SABADO,"
  +" PRA.PRA_HR_FINAL,"
  +" PRA.PRA_IN_HORAS    AS pra_in_horas,"
  +" PRA1.PRA_IN_HORAS   AS pra_in_horasU,"
  +" PRA1.PRA_IN_DIAS    AS pra_in_diasU,"
  +" PRA1.PRA_CH_SEGUNDA AS pra_ch_segundaU,"
  +" PRA1.PRA_CH_TERCA   AS pra_ch_tercaU,"
  +" PRA1.PRA_CH_QUARTA  AS pra_ch_quartaU,"
  +" PRA1.PRA_CH_QUINTA  AS pra_ch_quintaU,"
  +" PRA1.PRA_CH_SEXTA   AS pra_ch_sextaU,"
  +" PRA1.PRA_CH_SABADO  AS pra_ch_sabadoU,"
  +" PRA1.PRA_CH_DOMINGO AS pra_ch_domingoU,"
  +" PRA1.PRA_HR_FINAL   AS PRA_HR_FINALU,"
  +" EXU.EXU_ST_PRAZOURGENTE,"
  +" EXU.EXU_CH_NAONECESSARIO,"
  +" ORI.ORI_ST_CODIGO,"
  +" ORI.ORI_CH_URGENCIA,"
  +" ORI.LEG_ST_CODIGOINICIAL,"
  +" ORI_CH_CONFEREAUTOMATICO,"
  +" ORI_CH_CONFEREAUTOMATICOFAT,"
  +" EXU.SET_ST_CODIGO,"
  +" EXU.EXU_ST_UNIDADEEX,"
  +" EXU.EXU_ST_UNIDADEEXURGENTE,"
  +" EXU.EXU_CH_CONFEREAUTOMATICOFAT,"
  +" (SELECT MAX(EXA_ST_CODIGO)"
  +" FROM LAB_EXAMEDEPENDENTE"
  +" WHERE UNI_ST_CODIGO =?"//uniStCodigo 13
  +" AND EXA_ST_CODIGO   =?"//exaStCodigo 14
  +" ) AS DEP_ST_CODIGO"
+" FROM LAB_EXAME EXA,"
  +" LAB_EXAMEUNIDADE EXU,"
  +" LAB_METODO MET,"
  +" LAB_MATERIAL MAT,"
  +" LAB_EXAMEMETODO EXM,"
  +" LAB_PRAZO PRA,"
  +" LAB_PRAZO PRA1,"
  +" LAB_ORIGEM ORI,"
  +" LAB_EXAMETABELAPRECO ETP1,"
  +" LAB_TABELA TAB1,"
  +" LAB_REGRATABELAPRECO RTP1,"
  +" LAB_REGRAS REG1,"
  +" LAB_TABELAPRECO TAP1"
+" WHERE EXU.EXA_ST_CODIGO        = EXA.EXA_ST_CODIGO"
+" AND ORI.UNI_ST_CODIGO          = EXU.UNI_ST_CODIGO"
+" AND EXU.EXU_ST_PRAZOURGENTE    = PRA1.PRA_ST_CODIGO(+)"
+" AND EXU.MET_ST_CODIGO          = MET.MET_ST_CODIGO(+)"
+" AND EXA.MAT_ST_COLETA          = MAT.MAT_ST_CODIGO(+)"
+" AND EXU.PRA_ST_CODIGO          = PRA.PRA_ST_CODIGO(+)"
+" AND EXU.EXA_ST_CODIGO          = EXM.EXA_ST_CODIGO(+)"
+" AND EXU.MET_ST_CODIGO          = EXM.MET_ST_CODIGO(+)"
+" AND REG1.uni_st_codigo         = RTP1.uni_st_codigo"
+" AND REG1.con_st_codigo         = RTP1.con_st_codigo"
+" AND REG1.reg_st_codigo         = RTP1.reg_st_codigo"
+" AND ETP1.tap_st_codigo         = TAB1.tap_st_codigo"
+" AND ETP1.tab_st_codigo         = TAB1.tab_st_codigo"
+" AND TAB1.TAB_CH_TIPO           = '1'"
+" AND TAB1.TAB_DT_INICIOVALIDADE ="
  +" (SELECT MAX(TAB_DT_INICIOVALIDADE)"
  +" FROM LAB_TABELA"
  +" WHERE tap_st_codigo        = TAB1.tap_st_codigo"
  +" AND tab_st_codigo          = TAB1.tab_st_codigo"
  +" AND TAB_CH_TIPO            = '1'"
  +" AND TAB_DT_INICIOVALIDADE <= TO_DATE(?,'YYYY-MM-DD')"//Date 15
  +" )"
+" AND ETP1.tap_st_codigo         = RTP1.tap_st_codigo"
+" AND TAB1.tap_st_codigo         = TAP1.tap_st_codigo"
+" AND RTP1.uni_st_codigo         = EXU.UNI_ST_CODIGO"
+" AND ETP1.exa_st_codigo         = EXA.EXA_ST_CODIGO"
+" AND RTP1.RTP_DT_INICIOVALIDADE ="
  +" (SELECT MAX(RTP_DT_INICIOVALIDADE)"
  +" FROM LAB_REGRATABELAPRECO"
  +" WHERE uni_st_codigo        = RTP1.uni_st_codigo"
  +" AND con_st_codigo          = RTP1.con_st_codigo"
  +" AND reg_st_codigo          = RTP1.reg_st_codigo"
  +" AND RTP_DT_INICIOVALIDADE <= SYSDATE"
  +" AND RTP1.RTP_IN_SEQUENCIA  ="
    +" (SELECT MIN(RTP2.RTP_IN_SEQUENCIA)"
    +" FROM LAB_EXAMETABELAPRECO ETP2,"
      +" LAB_TABELA TAB2,"
      +" LAB_REGRATABELAPRECO RTP2,"
      +" LAB_TABELAPRECO TAP2"
    +" WHERE ETP2.tap_st_codigo       = TAB2.tap_st_codigo"
    +" AND ETP2.tab_st_codigo         = TAB2.tab_st_codigo"
    +" AND TAB2.TAB_CH_TIPO           = '1'"
    +" AND RTP2.uni_st_codigo         = RTP2.uni_st_codigo"
    +" AND RTP2.con_st_codigo         = RTP2.con_st_codigo"
    +" AND RTP2.reg_st_codigo         = RTP2.reg_st_codigo"
    +" AND ETP2.tap_st_codigo         = RTP2.tap_st_codigo"
    +" AND TAB2.tap_st_codigo         = TAP2.tap_st_codigo"
    +" AND RTP2.uni_st_codigo         = RTP1.UNI_ST_CODIGO"
    +" AND RTP2.con_st_codigo         = RTP1.CON_ST_CODIGO"
    +" AND RTP2.reg_st_codigo         = RTP1.REG_ST_CODIGO"
    +" AND ETP2.TAP_ST_CODIGO         = ETP2.TAP_ST_CODIGO"
    +" AND ETP2.exa_st_codigo         = ETP1.EXA_ST_CODIGO"
    +" AND RTP2.RTP_DT_INICIOVALIDADE ="
      +" (SELECT MAX(RTP_DT_INICIOVALIDADE)"
      +" FROM LAB_REGRATABELAPRECO"
      +" WHERE uni_st_codigo       = RTP1.uni_st_codigo"
      +" AND con_st_codigo         = RTP1.con_st_codigo"
      +" AND reg_st_codigo         = RTP1.reg_st_codigo"
      +" AND tap_st_codigo         = ETP1.tap_st_codigo"
      +" AND RTP_DT_INICIOVALIDADE = RTP1.Rtp_Dt_Iniciovalidade"
      +" )"
    +" )"
  +" )"
+" AND EXU.UNI_ST_CODIGO  =?"//uniStCodigo 16
+" AND RTP1.CON_ST_CODIGO =?"//conStCodigo 17
+" AND RTP1.REG_ST_CODIGO =?"//regStCodigo 18
+" AND ORI.ORI_ST_CODIGO  =?"//oriStCodigo 19
+" AND EXA.EXA_ST_CODIGO  =?";//exaStCodigo 20



      public static String QUERY4EXAMEFORMATADOGRUPO =
    "  SELECT "
  +" 0        AS TAB_FL_QTDECH,"
  +" 0             AS RTP_FL_VALORCH,"
  +" 0             AS RTP_FL_VALORCHEXTERNO,"
  +" 0             AS RTP_FL_DESCONTO,"
  +" 0             AS RTP_FL_DESCONTOEXTERNO,"
  +" 0             AS RTP_FL_ACRESCIMO,"
  +" EXD_ST_TABELA AS TAP_ST_CODIGO,"
  +" REG.REG_CH_OBRIGATORIONUMGUIA,"
  +" EXD_ST_CODIGO           AS TAB_ST_CODIGO,"
  +" ''                      AS TAP_ST_DESCRICAO,"
  +" EDI.EDI_FL_VALOR        AS ETP_FL_VALORDIFENCIADO,"
  +" EDI.EDI_FL_VALOREXTERNO AS ETP_FL_VALORDIFENCIADOEXTERNO,"
  +" EDI.EDI_FL_DESCONTO,"
  +" EDI.EDI_FL_DESCONTOEXTERNO,"
 +" (SELECT"
 +" CASE"
 +" WHEN COUNT(*) > 0"
 +" THEN 'S'"
 +" ELSE 'N'"
 +" END"
 +" FROM LAB_EXAMESCOMAUTORIZACAO"
 +" WHERE UNI_ST_CODIGO = EDI.UNI_ST_CODIGO"
 +" AND CON_ST_CODIGO   = EDI.CON_ST_CODIGO"
 +" AND REG_ST_CODIGO   = EDI.REG_ST_CODIGO"
 +" AND EXA_ST_CODIGO   = EDI.EXA_ST_CODIGO"
 +" ) AS ETP_ch_comautorizacao,"
 +" (SELECT"
 +" CASE"
 +" WHEN COUNT(*) > 0"
 +" THEN 'S'"
 +" ELSE 'N'"
 +" END"
 +" FROM LAB_EXAMENAOAUTORIZADOS"
 +" WHERE UNI_ST_CODIGO = EDI.UNI_ST_CODIGO"
 +" AND CON_ST_CODIGO   = EDI.CON_ST_CODIGO"
 +" AND REG_ST_CODIGO   = EDI.REG_ST_CODIGO"
 +" AND EXA_ST_CODIGO   = EDI.EXA_ST_CODIGO"
 +" ) AS ETP_ch_naoautorizado,"
 +" (SELECT EXA_CH_OBRIGAGESTANTE FROM LAB_EXAME WHERE EXA_ST_CODIGO= ? " // 1 '"+exaStCodigo+"'
 +" ) AS EXA_CH_OBRIGAGESTANTE,"
 +" (SELECT EXA_CH_SEXO FROM LAB_EXAME WHERE EXA_ST_CODIGO= ?" //  2 '"+exaStCodigo+"'
 +" ) AS EXA_CH_SEXO,"
 +" MAT.MAT_ST_CODIGO,"
 +" MAT.MAT_ST_DESCRICAO,"
 +" EXG.EXA_ST_CODIGO,"
 +" EXA.EXA_CH_OBRIGATORIOPESO,"
  +" EXA.EXA_ST_DESCRICAO,"
 +" EXA.EXA_CH_OBRIGATORIOALTURA,"
 +" EXA.EXA_CH_OBRIGAGESTANTE,"
 +" EXA.EXA_CH_SEXO,"
 +" EXA.EXA_CH_GRUPO,"
 +" EXA.EXA_CH_INATIVO,"
 +" EXU.EXU_CH_PREPARO,"
 +" EXU.MPA_ST_CODIGO,"
 +" EXU.MET_ST_CODIGO,"
 +" EXU.EXU_CH_obrigamaterial,"
 +" EXU.PRA_ST_CODIGO,"
 +" EXU.EXU_ST_PRAZOURGENTE,"
 +" EXU.EXU_ST_UNIDADEEX,"
 +" EXU.SET_ST_CODIGO,"
 +" EXU.EXU_ST_UNIDADEEXURGENTE,"
 +" EXU.EXU_CH_CONFEREAUTOMATICOFAT,"
 +" PRA.PRA_IN_DIAS,"
 +" PRA.PRA_IN_HORAS AS pra_in_horas,"
 +" PRA.PRA_CH_DOMINGO,"
 +" PRA.PRA_CH_SEGUNDA,"
 +" PRA.PRA_CH_TERCA,"
 +" PRA.PRA_CH_QUARTA,"
 +" PRA.PRA_CH_QUINTA,"
 +" PRA.PRA_CH_SEXTA,"
 +" PRA.PRA_CH_SABADO,"
 +" PRA.PRA_HR_FINAL,"
 +" PRA1.PRA_IN_HORAS   AS pra_in_horasU,"
 +" PRA1.PRA_IN_DIAS    AS pra_in_diasU,"
 +" PRA1.PRA_CH_SEGUNDA AS pra_ch_segundaU,"
 +" PRA1.PRA_CH_TERCA   AS pra_ch_tercaU,"
 +" PRA1.PRA_CH_QUARTA  AS pra_ch_quartaU,"
 +" PRA1.PRA_CH_QUINTA  AS pra_ch_quintaU,"
 +" PRA1.PRA_CH_SEXTA   AS pra_ch_sextaU,"
 +" PRA1.PRA_CH_SABADO  AS pra_ch_sabadoU,"
 +" PRA1.PRA_CH_DOMINGO AS pra_ch_domingoU,"
 +" PRA1.PRA_HR_FINAL   AS PRA_HR_FINALU,"
 +" MET.MET_ST_DESCRICAO,"
 +" ORI.ORI_ST_CODIGO,"
 +" ORI.ORI_CH_URGENCIA,"
 +" ORI.LEG_ST_CODIGOINICIAL,"
 +" ORI.ORI_CH_CONFEREAUTOMATICO,"
 +" ORI.ORI_CH_CONFEREAUTOMATICOFAT,"
 +" EXM.EXM_DT_VALIDADE,"
 +" CASE"
 +" WHEN (EXU.EXU_CH_NAONECESSARIO = 'S'"
 +" OR EXG.EXG_CH_OMITE            = 'S')"
 +" THEN 'S'"
 +" ELSE 'N'"
 +" END AS EXU_CH_NAONECESSARIO,"
 +" (SELECT"
 +" CASE"
 +" WHEN COUNT(*) > 0"
 +" THEN 'S'"
 +" ELSE 'N'"
 +" END"
 +" FROM LAB_EXAMENAOAUTORIZADOS"
 +" WHERE UNI_ST_CODIGO = EDI.UNI_ST_CODIGO"
 +" AND CON_ST_CODIGO   = EDI.CON_ST_CODIGO"
 +" AND REG_ST_CODIGO   = EDI.REG_ST_CODIGO"
 +" AND EXA_ST_CODIGO   = EDI.EXA_ST_CODIGO"
 +" ) AS ETP_ch_naoautorizadoG,"
 +" EXU.EXU_CH_SOFATURAMENTO,"
 +" EXU.EXU_CH_FATURA,"
 +" EXG.SEQ_ST_CODIGO,"
 +" EXG.EXG_CH_FATURA,"
 +" SEQ.SEQ_ST_DESCRICAO,"
 +" (SELECT EXMG.EXM_DT_VALIDADE"
 +" FROM LAB_EXAMEMETODO EXMG"
 +" WHERE EXMG.EXA_ST_CODIGO = ? " // 3 '"+exaStCodigo+"'
 +" AND EXMG.MET_ST_CODIGO   ="
 +" (SELECT MET_ST_CODIGO"
 +" FROM LAB_EXAMEUNIDADE"
 +" WHERE UNI_ST_CODIGO = EXG.UNI_ST_CODIGO"
 +" AND EXA_ST_CODIGO   = EXG.GRP_ST_CODIGO"
 +" )"
 +" ) AS EXM_DT_VALIDADEGRUPO,"
 +" (SELECT EXUG.EXU_CH_FATURAGRUPO"
 +" FROM LAB_EXAMEUNIDADE EXUG"
 +" WHERE EXUG.UNI_ST_CODIGO = EXG.UNI_ST_CODIGO"
 +" AND EXUG.EXA_ST_CODIGO   = EXG.GRP_ST_CODIGO"
 +" ) AS EXU_CH_FATURAGRUPO,"
 +" (SELECT EXAG1.EXA_ST_DESCRICAO"
 +" FROM LAB_EXAME EXAG1"
 +" WHERE EXAG1.EXA_ST_CODIGO = EXG.EXA_ST_CODIGO"
 +" ) AS EXA_ST_DESCRICAOGRUPO,"
 +" (SELECT EXUG.EXU_CH_INATIVO"
 +" FROM LAB_EXAMEUNIDADE EXUG"
 +" WHERE EXUG.UNI_ST_CODIGO = EXG.UNI_ST_CODIGO"
 +" AND EXUG.EXA_ST_CODIGO   = EXG.GRP_ST_CODIGO"
 +" ) AS EXU_CH_INATIVOG,"
 +" (SELECT MET_ST_CODIGO"
 +" FROM LAB_EXAMEUNIDADE"
 +" WHERE UNI_ST_CODIGO = EXG.UNI_ST_CODIGO"
 +" AND EXA_ST_CODIGO   = EXG.GRP_ST_CODIGO"
 +" )        AS MET_ST_CODIGOGRP,"
 +" '      ' AS UNIDADEEX"
 +" FROM LAB_EXAMESDIFERENCIADOS EDI,"
 +" LAB_REGRAS REG,"
 +" LAB_EXAMEUNIDADE EXU,"
 +" LAB_ORIGEM ORI,"
 +" LAB_PRAZO PRA1,"
 +" LAB_PRAZO PRA,"
 +" LAB_EXAME EXA,"
 +" LAB_EXAMEMETODO EXM,"
 +" LAB_METODO MET,"
 +" LAB_SEQUENCIAAMOSTRA SEQ,"
 +" LAB_MATERIAL MAT,"
 +" LAB_EXAMEGRUPO EXG"
 +" WHERE EDI.UNI_ST_CODIGO     = REG.UNI_ST_CODIGO"
 +" AND EDI.CON_ST_CODIGO       = REG.CON_ST_CODIGO"
 +" AND EDI.REG_ST_CODIGO       = REG.REG_ST_CODIGO"
 +" AND EDI.UNI_ST_CODIGO       = EXU.UNI_ST_CODIGO"
 +" AND EDI.EXA_ST_CODIGO       = EXU.EXA_ST_CODIGO"
 +" AND EDI.UNI_ST_CODIGO       = ORI.UNI_ST_CODIGO"
 +" AND EXU.EXA_ST_CODIGO       = EXA.EXA_ST_CODIGO"
 +" AND EXU.EXU_ST_PRAZOURGENTE = PRA1.PRA_ST_CODIGO(+)"
 +" AND EXU.PRA_ST_CODIGO       = PRA.PRA_ST_CODIGO(+)"
 +" AND EXU.EXA_ST_CODIGO       = EXM.EXA_ST_CODIGO(+)"
 +" AND EXU.MET_ST_CODIGO       = EXM.MET_ST_CODIGO(+)"
 +" AND EXU.MET_ST_CODIGO       = MET.MET_ST_CODIGO(+)"
 +" AND EXA.MAT_ST_COLETA       = MAT.MAT_ST_CODIGO(+)"
 +" AND EXG.SEQ_ST_CODIGO       = SEQ.SEQ_ST_CODIGO (+)"
 +" AND EXG.UNI_ST_CODIGO       = EDI.UNI_ST_CODIGO (+)"
 +" AND EXG.EXA_ST_CODIGO       = EDI.EXA_ST_CODIGO (+)"
 +" AND EXG.UNI_ST_CODIGO       = ? " //4 '"+uniStCodigo+"'
 +" AND EXG.GRP_ST_CODIGO       = ? " //5 '"+exaStCodigo+"'
 +" AND ORI.ORI_ST_CODIGO       = ? " //6 '"+oriStCodigo+"'
 +" AND EDI.CON_ST_CODIGO       =? "  //7 '"+conStCodigo+"'
 +" AND EDI.REG_ST_CODIGO       =? " //8 '"+regStCodigo+"'
 +" AND EDI_DT_INICIOVALIDADE   ="
 +" (SELECT MAX(EDI_DT_INICIOVALIDADE)"
 +" FROM LAB_EXAMESDIFERENCIADOS"
 +" WHERE UNI_ST_CODIGO        = EDI.UNI_ST_CODIGO"
 +" AND CON_ST_CODIGO          = EDI.CON_ST_CODIGO"
 +" AND REG_ST_CODIGO          = EDI.REG_ST_CODIGO"
 +" AND EXA_ST_CODIGO          = EDI.EXA_ST_CODIGO"
 +" AND EDI_DT_INICIOVALIDADE <= TO_DATE (?,'YYYY-MM-DD'))"//9 '"+sdf.format(reqDtCadastro)+"'  /*  ('+#39 + cData_InicioValidade + #39+','+Quotedstr(YYYY-MM-DD) */
 +" UNION ALL"
 +" SELECT TAB1.TAB_FL_QTDECH,"
 +" RTP1.rtp_fl_valorch,"
 +" RTP1.RTP_FL_VALORCHEXTERNO,"
 +" RTP1.rtp_fl_desconto,"
 +" RTP1.rtp_fl_descontoEXTERNO,"
 +" RTP1.rtp_fl_acrescimo,"
 +" RTP1.TAP_ST_CODIGO,"
 +" REG1.REG_CH_OBRIGATORIONUMGUIA,"
 +" TAB1.TAB_ST_CODIGO,"
 +" TAP1.tap_st_descricao,"
 +" 0 AS ETP_fl_valordifenciado,"
 +" 0 AS ETP_fl_valordifenciadoExterno,"
 +" 0 AS EDI_FL_DESCONTO,"
 +" 0 AS EDI_FL_DESCONTOEXTERNO,"
 +" (SELECT"
 +" CASE"
 +" WHEN COUNT(*) > 0"
 +" THEN 'S'"
 +" ELSE 'N'"
 +" END"
 +" FROM LAB_EXAMESCOMAUTORIZACAO"
 +" WHERE UNI_ST_CODIGO = RTP1.UNI_ST_CODIGO"
 +" AND CON_ST_CODIGO   = RTP1.CON_ST_CODIGO"
 +" AND REG_ST_CODIGO   = RTP1.REG_ST_CODIGO"
 +" AND EXA_ST_CODIGO   = ETP1.EXA_ST_CODIGO"
 +" ) AS ETP_ch_comautorizacao,"
 +" (SELECT"
 +" CASE"
 +" WHEN COUNT(*) > 0"
 +" THEN 'S'"
 +" ELSE 'N'"
 +" END"
 +" FROM LAB_EXAMENAOAUTORIZADOS"
 +" WHERE UNI_ST_CODIGO = RTP1.UNI_ST_CODIGO"
 +" AND CON_ST_CODIGO   = RTP1.CON_ST_CODIGO"
 +" AND REG_ST_CODIGO   = RTP1.REG_ST_CODIGO"
 +" AND EXA_ST_CODIGO   = ETP1.EXA_ST_CODIGO"
 +" ) AS ETP_ch_naoautorizado,"
 +" (SELECT EXA_CH_OBRIGAGESTANTE FROM LAB_EXAME WHERE EXA_ST_CODIGO=? " //10 '"+exaStCodigo+"'
 +" ) AS EXA_CH_OBRIGAGESTANTE,"
 +" (SELECT EXA_CH_SEXO FROM LAB_EXAME WHERE EXA_ST_CODIGO=? "//11 '"+exaStCodigo+"'
 +" ) AS EXA_CH_SEXO,"
 +" MAT.MAT_ST_CODIGO,"
 +" MAT.MAT_ST_DESCRICAO,"
 +" EXA.EXA_ST_CODIGO,"
 +" EXA.EXA_CH_OBRIGATORIOPESO,"
 +" EXA.EXA_ST_DESCRICAO,"
 +" EXA.EXA_CH_OBRIGATORIOALTURA,"
 +" EXA.EXA_CH_OBRIGAGESTANTE,"
 +" EXA.EXA_CH_SEXO,"
 +" EXA.EXA_CH_GRUPO,"
 +" EXA.EXA_CH_INATIVO,"
 +" EXU.EXU_CH_PREPARO,"
 +" EXU.MPA_ST_CODIGO,"
 +" EXU.MET_ST_CODIGO,"
 +" EXU.EXU_CH_obrigamaterial,"
 +" EXU.PRA_ST_CODIGO,"
 +" EXU.EXU_ST_PRAZOURGENTE,"
 +" EXU.EXU_ST_UNIDADEEX,"
 +" EXU.SET_ST_CODIGO,"
 +" EXU.EXU_ST_UNIDADEEXURGENTE,"
 +" EXU.EXU_CH_CONFEREAUTOMATICOFAT,"
 +" PRA.PRA_IN_DIAS,"
 +" PRA.PRA_IN_HORAS AS pra_in_horas,"
 +" PRA.PRA_CH_DOMINGO,"
 +" PRA.PRA_CH_SEGUNDA,"
 +" PRA.PRA_CH_TERCA,"
 +" PRA.PRA_CH_QUARTA,"
 +" PRA.PRA_CH_QUINTA,"
 +" PRA.PRA_CH_SEXTA,"
 +" PRA.PRA_CH_SABADO,"
 +" PRA.PRA_HR_FINAL,"
 +" PRA1.PRA_IN_HORAS   AS pra_in_horasU,"
 +" PRA1.PRA_IN_DIAS    AS pra_in_diasU,"
 +" PRA1.PRA_CH_SEGUNDA AS pra_ch_segundaU,"
 +" PRA1.PRA_CH_TERCA   AS pra_ch_tercaU,"
 +" PRA1.PRA_CH_QUARTA  AS pra_ch_quartaU,"
 +" PRA1.PRA_CH_QUINTA  AS pra_ch_quintaU,"
 +" PRA1.PRA_CH_SEXTA   AS pra_ch_sextaU,"
 +" PRA1.PRA_CH_SABADO  AS pra_ch_sabadoU,"
 +" PRA1.PRA_CH_DOMINGO AS pra_ch_domingoU,"
 +" PRA1.PRA_HR_FINAL   AS PRA_HR_FINALU,"
 +" MET.MET_ST_DESCRICAO,"
 +" ORI.ORI_ST_CODIGO,"
 +" ORI.ORI_CH_URGENCIA,"
 +" ORI.LEG_ST_CODIGOINICIAL,"
 +" ORI_CH_CONFEREAUTOMATICO,"
 +" ORI_CH_CONFEREAUTOMATICOFAT,"
 +" EXM.EXM_DT_VALIDADE,"
 +" CASE"
 +" WHEN (EXU.EXU_CH_NAONECESSARIO = 'S'"
 +" OR EXG.EXG_CH_OMITE            = 'S')"
 +" THEN 'S'"
 +" ELSE 'N'"
 +" END AS EXU_CH_NAONECESSARIO,"
 +" (SELECT"
 +" CASE"
 +" WHEN COUNT(*) > 0"
 +" THEN 'S'"
 +" ELSE 'N'"
 +" END"
 +" FROM LAB_EXAMENAOAUTORIZADOS"
 +" WHERE UNI_ST_CODIGO = RTP1.UNI_ST_CODIGO"
 +" AND CON_ST_CODIGO   = RTP1.CON_ST_CODIGO"
 +" AND REG_ST_CODIGO   = RTP1.REG_ST_CODIGO"
 +" AND EXA_ST_CODIGO   = EXG.GRP_ST_CODIGO"
 +" ) AS ETP_ch_naoautorizadoG,"
 +" EXU.EXU_CH_SOFATURAMENTO,"
 +" EXU.EXU_CH_FATURA,"
 +" EXG.SEQ_ST_CODIGO,"
 +" EXG.EXG_CH_FATURA,"
 +" SEQ.SEQ_ST_DESCRICAO,"
 +" (SELECT EXMG.EXM_DT_VALIDADE"
 +" FROM LAB_EXAMEMETODO EXMG"
 +" WHERE EXMG.EXA_ST_CODIGO =? "//12 '"+exaStCodigo+"'
 +" AND EXMG.MET_ST_CODIGO   ="
 +" (SELECT MET_ST_CODIGO"
 +" FROM LAB_EXAMEUNIDADE"
 +" WHERE UNI_ST_CODIGO = EXG.UNI_ST_CODIGO"
 +" AND EXA_ST_CODIGO   = EXG.GRP_ST_CODIGO"
 +" )"
 +" ) AS EXM_DT_VALIDADEGRUPO,"
 +" (SELECT EXUG.EXU_CH_FATURAGRUPO"
 +" FROM LAB_EXAMEUNIDADE EXUG"
 +" WHERE EXUG.UNI_ST_CODIGO = EXG.UNI_ST_CODIGO"
 +" AND EXUG.EXA_ST_CODIGO   = EXG.GRP_ST_CODIGO"
 +" ) AS EXU_CH_FATURAGRUPO,"
 +" (SELECT EXAG1.EXA_ST_DESCRICAO"
 +" FROM LAB_EXAME EXAG1"
 +" WHERE EXAG1.EXA_ST_CODIGO = EXG.GRP_ST_CODIGO"
 +" ) AS EXA_ST_DESCRICAOGRUPO,"
 +" (SELECT EXUG.EXU_CH_INATIVO"
 +" FROM LAB_EXAMEUNIDADE EXUG"
 +" WHERE EXUG.UNI_ST_CODIGO = EXG.UNI_ST_CODIGO"
 +" AND EXUG.EXA_ST_CODIGO   = EXG.GRP_ST_CODIGO"
 +" ) AS EXU_CH_INATIVOG,"
 +" (SELECT MET_ST_CODIGO"
 +" FROM LAB_EXAMEUNIDADE"
 +" WHERE UNI_ST_CODIGO = EXG.UNI_ST_CODIGO"
 +" AND EXA_ST_CODIGO   = EXG.GRP_ST_CODIGO"
 +" )        AS MET_ST_CODIGOGRP,"
 +" '      ' AS UNIDADEEX"
 +" FROM LAB_EXAMEGRUPO EXG,"
 +" LAB_EXAME EXA,"
 +" LAB_EXAMEUNIDADE EXU,"
 +" LAB_METODO MET,"
 +" LAB_MATERIAL MAT,"
 +" LAB_EXAMEMETODO EXM,"
 +" LAB_SEQUENCIAAMOSTRA SEQ,"
 +" LAB_PRAZO PRA,"
 +" LAB_PRAZO PRA1,"
 +" LAB_ORIGEM ORI,"
 +" LAB_EXAMETABELAPRECO ETP1,"
 +" LAB_TABELA TAB1,"
 +" LAB_REGRATABELAPRECO RTP1,"
 +" LAB_TABELAPRECO TAP1,"
 +" LAB_REGRAS REG1"
 +" WHERE EXG.EXA_ST_CODIGO        = EXA.EXA_ST_CODIGO"
 +" AND EXU.MET_ST_CODIGO          = MET.MET_ST_CODIGO"
 +" AND EXU.EXA_ST_CODIGO          = EXM.EXA_ST_CODIGO"
 +" AND EXU.MET_ST_CODIGO          = EXM.MET_ST_CODIGO"
 +" AND EXA.MAT_ST_COLETA          = MAT.MAT_ST_CODIGO"
 +" AND EXU.EXA_ST_CODIGO          = EXA.EXA_ST_CODIGO"
 +" AND EXU.PRA_ST_CODIGO          = PRA.PRA_ST_CODIGO(+)"
 +" AND EXU.EXU_ST_PRAZOURGENTE    = PRA1.PRA_ST_CODIGO(+)"
 +" AND EXG.SEQ_ST_CODIGO          = SEQ.SEQ_ST_CODIGO"
 +" AND ORI.UNI_ST_CODIGO          = EXU.UNI_ST_CODIGO"
 +" AND ETP1.tap_st_codigo         = TAB1.tap_st_codigo"
 +" AND ETP1.tab_st_codigo         = TAB1.tab_st_codigo"
 +" AND TAB1.TAB_CH_TIPO           = '1'"
 +" AND TAB1.TAB_DT_INICIOVALIDADE ="
 +" (SELECT MAX(TAB_DT_INICIOVALIDADE)"
 +" FROM LAB_TABELA"
 +" WHERE tap_st_codigo        = TAB1.tap_st_codigo"
 +" AND tab_st_codigo          = TAB1.tab_st_codigo"
 +" AND TAB_CH_TIPO            = '1'"
 +" AND TAB_DT_INICIOVALIDADE <= TO_DATE (?,'YYYY-MM-DD') )" //13 '"+sdf.format(reqDtCadastro)+"'
 +" AND REG1.uni_st_codigo         = RTP1.uni_st_codigo"
 +" AND REG1.con_st_codigo         = RTP1.con_st_codigo"
 +" AND REG1.reg_st_codigo         = RTP1.reg_st_codigo"
 +" AND ETP1.tap_st_codigo         = RTP1.tap_st_codigo"
 +" AND TAB1.tap_st_codigo         = TAP1.tap_st_codigo"
 +" AND RTP1.uni_st_codigo         = EXU.UNI_ST_CODIGO"
 +" AND ETP1.exa_st_codigo         = EXA.EXA_ST_CODIGO"
 +" AND RTP1.RTP_DT_INICIOVALIDADE ="
 +" (SELECT MAX(RTP_DT_INICIOVALIDADE)"
 +" FROM LAB_REGRATABELAPRECO"
 +" WHERE uni_st_codigo        = RTP1.uni_st_codigo"
 +" AND con_st_codigo          = RTP1.con_st_codigo"
 +" AND reg_st_codigo          = RTP1.reg_st_codigo"
 +" AND RTP_DT_INICIOVALIDADE <= SYSDATE"
 +" AND RTP1.RTP_IN_SEQUENCIA  ="
 +" (SELECT MIN(RTP2.RTP_IN_SEQUENCIA)"
 +" FROM LAB_EXAMETABELAPRECO ETP2,"
 +" LAB_TABELA TAB2,"
 +" LAB_REGRATABELAPRECO RTP2,"
 +" LAB_TABELAPRECO TAP2"
 +" WHERE ETP2.tap_st_codigo       = TAB2.tap_st_codigo"
 +" AND ETP2.tab_st_codigo         = TAB2.tab_st_codigo"
 +" AND TAB2.TAB_CH_TIPO           = '1'"
 +" AND RTP2.uni_st_codigo         = RTP2.uni_st_codigo"
 +" AND RTP2.con_st_codigo         = RTP2.con_st_codigo"
 +" AND RTP2.reg_st_codigo         = RTP2.reg_st_codigo"
 +" AND ETP2.tap_st_codigo         = RTP2.tap_st_codigo"
 +" AND TAB2.tap_st_codigo         = TAP2.tap_st_codigo"
 +" AND RTP2.uni_st_codigo         = RTP1.UNI_ST_CODIGO"
 +" AND RTP2.con_st_codigo         = RTP1.CON_ST_CODIGO"
 +" AND RTP2.reg_st_codigo         = RTP1.REG_ST_CODIGO"
 +" AND ETP2.TAP_ST_CODIGO         = ETP2.TAP_ST_CODIGO"
 +"  AND ETP2.exa_st_codigo         = ETP1.EXA_ST_CODIGO"
 +" AND RTP2.RTP_DT_INICIOVALIDADE ="
 +" (SELECT MAX(RTP_DT_INICIOVALIDADE)"
 +" FROM LAB_REGRATABELAPRECO"
 +" WHERE uni_st_codigo       = RTP1.uni_st_codigo"
 +" AND con_st_codigo         = RTP1.con_st_codigo"
 +" AND reg_st_codigo         = RTP1.reg_st_codigo"
 +" AND tap_st_codigo         = ETP1.tap_st_codigo"
 +" AND RTP_DT_INICIOVALIDADE = RTP1.Rtp_Dt_Iniciovalidade"
 +" )"
 +" )"
 +" )"
 +" AND EXU.UNI_ST_CODIGO =? "//14 '"+uniStCodigo+"'
 +" AND EXG.UNI_ST_CODIGO =? "//15 '"+uniStCodigo+"'
 +" AND RTP1.CON_ST_CODIGO=? "//16 '"+conStCodigo+"'
 +" AND RTP1.REG_ST_CODIGO=? "//17 '"+regStCodigo+"'
 +" AND ORI.ORI_ST_CODIGO =? "//18 '"+oriStCodigo+"'
 +" AND EXG.GRP_ST_CODIGO =? ";//19 '"+exaStCodigo+"'"




 public static String QUERY4EXAMEFORMATADODEPENDENTE =
  " SELECT"
+"                          0 AS TAB_FL_QTDECH,"
+"                          0 AS RTP_FL_VALORCH,"
+"                          0 AS RTP_FL_VALORCHEXTERNO,"
+"                          0 AS RTP_FL_DESCONTO,"
+"                          0 AS RTP_FL_DESCONTOEXTERNO,"
+"                          0 AS RTP_FL_ACRESCIMO,"
+"                          EXD_ST_TABELA AS TAP_ST_CODIGO,"
+"                          REG.REG_CH_OBRIGATORIONUMGUIA,"
+"                          EXD_ST_CODIGO AS TAB_ST_CODIGO,"
+"                          '' AS TAP_ST_DESCRICAO,"
+"                          EDI.EDI_FL_VALOR AS ETP_FL_VALORDIFENCIADO,"
+"                          EDI.EDI_FL_VALOREXTERNO AS ETP_FL_VALORDIFENCIADOEXTERNO,"
+"                          EDI.EDI_FL_DESCONTO,"
+"                          EDI.EDI_FL_DESCONTOEXTERNO,"
+"                          'N' AS ETP_CH_COMAUTORIZACAO,"
+"                          'N' AS ETP_CH_NAOAUTORIZADO,"
+"                          der.exa_st_codigo,"
+"                          dep.dep_st_codigo,"
+"                          DEP.DEP_CH_OMITE,"
+"                          dep.dep_ch_fatura,"
+"                          MAT.MAT_ST_CODIGO,"
+"                          MAT.MAT_ST_DESCRICAO,"
+"                          EXA.EXA_CH_OBRIGATORIOPESO,"
+"                          EXA.EXA_CH_OBRIGATORIOALTURA,"
+"                          EXA.EXA_CH_OBRIGAGESTANTE,"
+"                          EXA.EXA_CH_SEXO,"
+"                          EXU.MPA_ST_CODIGO,"
+"                          EXA.EXA_ST_DESCRICAO,"
+"                          EXU.EXU_CH_obrigamaterial,"
+"                          EXU.MET_ST_CODIGO,"
+"                          MET.MET_ST_DESCRICAO,"
+"                          EXM.EXM_DT_VALIDADE,"
+"                          EXU.EXU_CH_STATUS,"
+"                          EXU.EXU_CH_FATURA,"
+"                          EXA.EXA_CH_INATIVO,"
+"                          EXU.EXU_CH_PREPARO,"
+"                          EXA.EXA_CH_GRUPO,"
+"                          EXU.EXU_CH_INATIVO,"
+"                          EXU.PRA_ST_CODIGO,"
+"                          EXU.EXU_ST_UNIDADEEX,"
+"                          EXU.EXU_ST_UNIDADEEXURGENTE,"
+"                          EXU.EXU_CH_CONFEREAUTOMATICOFAT,"
+"                          PRA.PRA_IN_DIAS,"
+"                          PRA.PRA_CH_DOMINGO,"
+"                          PRA.PRA_CH_SEGUNDA,"
+"                          PRA.PRA_CH_TERCA,"
+"                          PRA.PRA_CH_QUARTA,"
+"                          PRA.PRA_CH_QUINTA,"
+"                          PRA.PRA_CH_SEXTA,"
+"                          PRA.PRA_CH_SABADO,"
+"                          PRA.PRA_HR_FINAL,"
+"                         EXU.EXU_ST_PRAZOURGENTE,"
+"                          PRA.PRA_IN_HORAS as pra_in_horas,"
+"                          PRA1.PRA_IN_HORAS as pra_in_horasU,"
+"                          EXU.APO_ST_CODIGO,"
+"                          PRA1.PRA_IN_DIAS as pra_in_diasU,"
+"                          PRA1.PRA_CH_SEGUNDA as pra_ch_segundaU,"
+"                          PRA1.PRA_CH_TERCA as pra_ch_tercaU,"
+"                          PRA1.PRA_CH_QUARTA as pra_ch_quartaU,"
+"                          PRA1.PRA_CH_QUINTA as pra_ch_quintaU,"
+"                          PRA1.PRA_CH_SEXTA as pra_ch_sextaU,"
+"                          PRA1.PRA_CH_SABADO as pra_ch_sabadoU,"
+"                          PRA1.PRA_CH_DOMINGO as pra_ch_domingoU,"
+"                          PRA1.PRA_HR_FINAL AS PRA_HR_FINALU,"
+"                          ORI.ORI_ST_CODIGO,"
+"                          ORI.ORI_CH_URGENCIA,"
+"                          ORI.LEG_ST_CODIGOINICIAL,"
+"                          ORI.ORI_CH_CONFEREAUTOMATICO,"
+"                          ORI.ORI_CH_CONFEREAUTOMATICOFAT,"
+"                          EXU.SET_ST_CODIGO,"
+"                          '      ' as UNIDADEEX"
+"                   FROM LAB_EXAMESDIFERENCIADOS EDI, LAB_REGRAS REG, LAB_EXAMEUNIDADE EXU, LAB_ORIGEM ORI,LAB_PRAZO PRA1,LAB_EXAMEDEPENDENTE DEP,"
+"                        LAB_PRAZO PRA,LAB_EXAME EXA, LAB_EXAMEMETODO EXM,LAB_METODO MET,LAB_MATERIAL MAT,lab_detalherequisicao der"
+"                    WHERE EDI.UNI_ST_CODIGO = REG.UNI_ST_CODIGO"
+"                      AND EDI.CON_ST_CODIGO = REG.CON_ST_CODIGO"
+"                      AND EDI.REG_ST_CODIGO = REG.REG_ST_CODIGO"
+"                      AND EDI.UNI_ST_CODIGO = EXU.UNI_ST_CODIGO"
+"                      AND EDI.EXA_ST_CODIGO = EXU.EXA_ST_CODIGO"
+"                      AND DER.EXA_ST_CODIGO = DEP.EXA_ST_CODIGO"
+"                      AND DER.UNI_ST_CODIGO = DEP.UNI_ST_CODIGO"
+"                      AND EXA.EXA_ST_CODIGO = DEP.DEP_ST_CODIGO"
+"                      AND EDI.UNI_ST_CODIGO = ORI.UNI_ST_CODIGO"
+"                      AND EXU.EXA_ST_CODIGO = EXA.EXA_ST_CODIGO"
+"                      AND EXU.EXU_ST_PRAZOURGENTE = PRA1.PRA_ST_CODIGO(+)"
+"                      AND EXU.PRA_ST_CODIGO = PRA.PRA_ST_CODIGO(+)"
+"                      AND EXU.EXA_ST_CODIGO = EXM.EXA_ST_CODIGO(+)"
+"                      AND EXU.MET_ST_CODIGO = EXM.MET_ST_CODIGO(+)"
+"                      AND EXU.MET_ST_CODIGO = MET.MET_ST_CODIGO(+)"
+"                      AND EXA.MAT_ST_COLETA = MAT.MAT_ST_CODIGO(+)"
+"                      AND EDI.UNI_ST_CODIGO =? "//1 '"+uniStCodigo+"'
+"                      AND ORI.ORI_ST_CODIGO =? "//2 '"+oriStCodigo+"'
+"                      AND EDI.CON_ST_CODIGO =? "//3 '"+conStCodigo+"'
+"                      AND EDI.REG_ST_CODIGO =? "//4 '"+regStCodigo+"'
+"                      and DER.REQ_ST_CODIGO =? "//5 '"+reqStCodigo+"'
+"                      AND EDI_DT_INICIOVALIDADE ="
+"                          (SELECT MAX(EDI_DT_INICIOVALIDADE) FROM LAB_EXAMESDIFERENCIADOS"
+"                            WHERE UNI_ST_CODIGO = EDI.UNI_ST_CODIGO"
+"                              AND CON_ST_CODIGO = EDI.CON_ST_CODIGO"
+"                              AND REG_ST_CODIGO = EDI.REG_ST_CODIGO"
+"                              AND EXA_ST_CODIGO = EDI.EXA_ST_CODIGO"
+"                              AND EDI_DT_INICIOVALIDADE <= TO_DATE(?,'YYYY-MM-DD'))"//6 '"+sdf.format(reqDtCadastro)+"'
+"                   UNION ALL"
+"                   select TAB1.TAB_FL_QTDECH,"
+"                          RTP1.rtp_fl_valorch,"
+"                          RTP1.rtp_fl_valorchEXTERNO,"
+"                          RTP1.rtp_fl_desconto,"
+"                          RTP1.rtp_fl_descontoEXTERNO,"
+"                          RTP1.rtp_fl_acrescimo,"
+"                          RTP1.TAP_ST_CODIGO,"
+"                          REG1.REG_CH_OBRIGATORIONUMGUIA,"
+"                          TAB1.TAB_ST_CODIGO,"
+"                          TAP1.tap_st_descricao,"
+"                          0 AS ETP_fl_valordifenciado,"
+"                          0 AS ETP_fl_valordifenciadoExterno,"
+"                          0 EDI_FL_DESCONTO,"
+"                          0 EDI_FL_DESCONTOEXTERNO,"
+"                          (SELECT CASE WHEN COUNT(*) > 0 THEN  'S'  ELSE  'N'  END"
+"                             FROM LAB_EXAMESCOMAUTORIZACAO"
+"                            WHERE UNI_ST_CODIGO = RTP1.UNI_ST_CODIGO"
+"                              AND CON_ST_CODIGO = RTP1.CON_ST_CODIGO"
+"                              AND REG_ST_CODIGO = RTP1.REG_ST_CODIGO"
+"                              AND EXA_ST_CODIGO = ETP1.EXA_ST_CODIGO) AS ETP_ch_comautorizacao,"
+"                          (SELECT CASE WHEN COUNT(*) > 0 THEN 'S' ELSE 'N' END FROM LAB_EXAMENAOAUTORIZADOS"
+"                            WHERE UNI_ST_CODIGO = RTP1.UNI_ST_CODIGO"
+"                              AND CON_ST_CODIGO = RTP1.CON_ST_CODIGO"
+"                              AND REG_ST_CODIGO = RTP1.REG_ST_CODIGO"
+"                              AND EXA_ST_CODIGO = ETP1.EXA_ST_CODIGO) AS ETP_ch_naoautorizado,"
+"                          der.exa_st_codigo,"
+"                          dep.dep_st_codigo,"
+"                          DEP.DEP_CH_OMITE,"
+"                          dep.dep_ch_fatura,"
+"                          MAT.MAT_ST_CODIGO,"
+"                          MAT.MAT_ST_DESCRICAO,"
+"                          EXA.EXA_CH_OBRIGATORIOPESO,"
+"                          EXA.EXA_CH_OBRIGATORIOALTURA,"
+"                          EXA.EXA_CH_OBRIGAGESTANTE,"
+"                          EXA.EXA_CH_SEXO,"
+"                          EXU.MPA_ST_CODIGO,"
+"                          EXA.EXA_ST_DESCRICAO,"
+"                          EXU.EXU_CH_obrigamaterial,"
+"                          EXU.MET_ST_CODIGO,"
+"                          MET.MET_ST_DESCRICAO,"
+"                          EXM.EXM_DT_VALIDADE,"
+"                          EXU.EXU_CH_STATUS,"
+"                          EXU.EXU_CH_FATURA,"
+"                          EXA.EXA_CH_INATIVO,"
+"                          EXU.EXU_CH_PREPARO,"
+"                          EXA.EXA_CH_GRUPO,"
+"                          EXU.EXU_CH_INATIVO,"
+"                          EXU.PRA_ST_CODIGO,"
+"                          EXU.EXU_ST_UNIDADEEX,"
+"                          EXU.EXU_ST_UNIDADEEXURGENTE,"
+"                          EXU.EXU_CH_CONFEREAUTOMATICOFAT,"
+"                          PRA.PRA_IN_DIAS,"
+"                          PRA.PRA_CH_DOMINGO,"
+"                          PRA.PRA_CH_SEGUNDA,"
+"                          PRA.PRA_CH_TERCA,"
+"                          PRA.PRA_CH_QUARTA,"
+"                          PRA.PRA_CH_QUINTA,"
+"                          PRA.PRA_CH_SEXTA,"
+"                          PRA.PRA_CH_SABADO,"
+"                          PRA.PRA_HR_FINAL,"
+"                          EXU.EXU_ST_PRAZOURGENTE,"
+"                          PRA.PRA_IN_HORAS as pra_in_horas,"
+"                          PRA1.PRA_IN_HORAS as pra_in_horasU,"
+"                          EXU.APO_ST_CODIGO,"
+"                          PRA1.PRA_IN_DIAS as pra_in_diasU,"
+"                          PRA1.PRA_CH_SEGUNDA as pra_ch_segundaU,"
+"                          PRA1.PRA_CH_TERCA as pra_ch_tercaU,"
+"                          PRA1.PRA_CH_QUARTA as pra_ch_quartaU,"
+"                          PRA1.PRA_CH_QUINTA as pra_ch_quintaU,"
+"                          PRA1.PRA_CH_SEXTA as pra_ch_sextaU,"
+"                          PRA1.PRA_CH_SABADO as pra_ch_sabadoU,"
+"                          PRA1.PRA_CH_DOMINGO as pra_ch_domingoU,"
+"                          PRA1.PRA_HR_FINAL AS PRA_HR_FINALU,"
+"                          ORI.ORI_ST_CODIGO,"
+"                          ORI.ORI_CH_URGENCIA,"
+"                          ORI.LEG_ST_CODIGOINICIAL,"
+"                          ori.ORI_CH_CONFEREAUTOMATICO,"
+"                          ori.ORI_CH_CONFEREAUTOMATICOFAT,"
+"                          EXU.SET_ST_CODIGO,"
+"                          '      ' as UNIDADEEX"
+"                     FROM lab_detalherequisicao der,"
+"                          lab_examedependente   dep,"
+"                          LAB_EXAME             EXA,"
+"                          LAB_EXAMEUNIDADE      EXU,"
+"                          LAB_METODO            MET,"
+"                          LAB_MATERIAL          MAT,"
+"                          LAB_EXAMEMETODO       EXM,"
+"                          LAB_PRAZO             PRA,"
+"                          LAB_PRAZO             PRA1,"
+"                          LAB_ORIGEM            ORI,"
+"                          LAB_EXAMETABELAPRECO  ETP1,"
+"                          LAB_TABELA            TAB1,"
+"                          LAB_REGRATABELAPRECO  RTP1,"
+"                          LAB_REGRAS            REG1,"
+"                          LAB_TABELAPRECO       TAP1"
+"                    WHERE der.exa_st_codigo = dep.exa_st_codigo"
+"                      AND der.uni_st_codigo = dep.uni_st_codigo"
+"                      AND EXU.MET_ST_CODIGO = MET.MET_ST_CODIGO"
+"                      AND EXA.MAT_ST_COLETA = MAT.MAT_ST_CODIGO"
+"                      AND EXU.PRA_ST_CODIGO = PRA.PRA_ST_CODIGO(+)"
+"                      AND EXU.EXU_ST_PRAZOURGENTE = PRA1.PRA_ST_CODIGO(+)"
+"                      AND EXU.EXA_ST_CODIGO = EXM.EXA_ST_CODIGO"
+"                      AND EXU.MET_ST_CODIGO = EXM.MET_ST_CODIGO"
+"                      AND EXU.EXA_ST_CODIGO = EXA.EXA_ST_CODIGO"
+"                      AND EXA.EXA_ST_CODIGO = dep.dep_st_codigo"
+"                      AND ORI.UNI_ST_CODIGO = EXU.UNI_ST_CODIGO"
+"                      AND REG1.uni_st_codigo = RTP1.uni_st_codigo"
+"                      AND REG1.con_st_codigo = RTP1.con_st_codigo"
+"                      AND REG1.reg_st_codigo = RTP1.reg_st_codigo"
+"                      AND ETP1.tap_st_codigo = TAB1.tap_st_codigo"
+"                      AND ETP1.tab_st_codigo = TAB1.tab_st_codigo"
+"                      AND TAB1.TAB_CH_TIPO = '1'"
+"                      AND TAB1.TAB_DT_INICIOVALIDADE ="
+"                          (SELECT MAX(TAB_DT_INICIOVALIDADE) FROM LAB_TABELA"
+"                            WHERE tap_st_codigo = TAB1.tap_st_codigo"
+"                                  AND tab_st_codigo = TAB1.tab_st_codigo"
+"                                  AND TAB_CH_TIPO = '1'"
+"                                  AND TAB_DT_INICIOVALIDADE <= TO_DATE(? ,'YYYY-MM-DD') )"//7 '"+sdf.format(reqDtCadastro)+"'
+"                      AND TAB1.tap_st_codigo = TAP1.tap_st_codigo"
+"                      AND RTP1.uni_st_codigo = EXU.UNI_ST_CODIGO"
+"                      AND ETP1.exa_st_codigo = EXA.EXA_ST_CODIGO"
+"                      AND RTP1.RTP_DT_INICIOVALIDADE ="
+"                          (SELECT MAX(RTP_DT_INICIOVALIDADE)"
+"                             FROM LAB_REGRATABELAPRECO"
+"                            WHERE uni_st_codigo = RTP1.uni_st_codigo"
+"                              AND con_st_codigo = RTP1.con_st_codigo"
+"                              AND reg_st_codigo = RTP1.reg_st_codigo"
+"                              AND RTP_DT_INICIOVALIDADE <= SYSDATE)"
+"                      AND RTP1.RTP_IN_SEQUENCIA ="
+"                          (SELECT MIN(RTP2.RTP_IN_SEQUENCIA)"
+"                             FROM LAB_EXAMETABELAPRECO ETP2,"
+"                                  LAB_TABELA           TAB2,"
+"                                  LAB_REGRATABELAPRECO RTP2,"
+"                                  LAB_TABELAPRECO      TAP2"
+"                            WHERE ETP2.tap_st_codigo = TAB2.tap_st_codigo"
+"                              AND ETP2.tab_st_codigo = TAB2.tab_st_codigo"
+"                              AND TAB2.TAB_CH_TIPO = '1'"
+"                              AND RTP2.uni_st_codigo = RTP2.uni_st_codigo"
+"                              AND RTP2.con_st_codigo = RTP2.con_st_codigo"
+"                              AND RTP2.reg_st_codigo = RTP2.reg_st_codigo"
+"                              AND ETP2.tap_st_codigo = RTP2.tap_st_codigo"
+"                              AND TAB2.tap_st_codigo = TAP2.tap_st_codigo"
+"                              AND RTP2.uni_st_codigo = RTP1.UNI_ST_CODIGO"
+"                              AND RTP2.con_st_codigo = RTP1.CON_ST_CODIGO"
+"                              AND RTP2.reg_st_codigo = RTP1.REG_ST_CODIGO"
+"                              AND ETP2.TAP_ST_CODIGO = ETP2.TAP_ST_CODIGO"
+"                              AND ETP2.exa_st_codigo = ETP1.EXA_ST_CODIGO"
+"                              AND RTP2.RTP_DT_INICIOVALIDADE ="
+"                                  (SELECT MAX(RTP_DT_INICIOVALIDADE)"
+"                                     FROM LAB_REGRATABELAPRECO"
+"                                    WHERE uni_st_codigo = RTP1.uni_st_codigo"
+"                                      AND con_st_codigo = RTP1.con_st_codigo"
+"                                      AND reg_st_codigo = RTP1.reg_st_codigo"
+"                                      AND tap_st_codigo = ETP1.tap_st_codigo"
+"                                      AND RTP_DT_INICIOVALIDADE = RTP1.Rtp_Dt_Iniciovalidade))"
+"                      AND EXU.UNI_ST_CODIGO ='TTT'"
+"                      AND RTP1.CON_ST_CODIGO =? "//8 '"+conStCodigo+"'
+"                      AND RTP1.REG_ST_CODIGO =? "//9 '"+regStCodigo+"'
  +"                    AND ORI.ORI_ST_CODIGO =? "     //10 '"+oriStCodigo+"'
  +"                 and DER.REQ_ST_CODIGO =? "  ;         //11 '"+reqStCodigo+"'




 public static String QUERY4USUARIOACCESS =

         "SELECT UMO.USU_ST_CODIGO USUUMO,"
       +" PUM.PUS_ST_CODIGO,"
       +" PUM.PUS_IN_SEQUENCIA,"
       +" PUM.PUS_IN_SEQUENCIAPAI,"
       +" PUM.MOD_ST_CODIGO,"
       +" PUM.PUS_CH_HABILITADO,"
       +" MDL.MOD_ST_DESCRICAO,"
       +" MDL.MOD_ST_FORMULARIO,"
       +" MDL.MOD_CH_STATUS,"
       +" MDL.MOD_ST_OPCAO1,"
       +" MDL.MOD_ST_OPCAO2,"
       +" MDL.MOD_ST_OPCAO3,"
       +" MDL.MOD_ST_OPCAO4,"
       +" MDL.MOD_ST_OPCAO5,"
       +" MDL.MOD_ST_OPCAO6,"
       +" MDL.MOD_ST_OPCAO7,"
       +" MDL.MOD_ST_OPCAO8,"
       +" MDL.MOD_ST_OPCAO9,"
       +" MDL.MOD_ST_OPCAO10,"
       +" UMO.UMO_CH_OPCAO1,"
       +" UMO.UMO_CH_OPCAO2,"
       +" UMO.UMO_CH_OPCAO3,"
       +" UMO.UMO_CH_OPCAO4,"
       +" UMO.UMO_CH_OPCAO5,"
       +" UMO.UMO_CH_OPCAO6,"
       +" UMO.UMO_CH_OPCAO7,"
       +" UMO.UMO_CH_OPCAO8,"
       +" UMO.UMO_CH_OPCAO9,"
       +" UMO.UMO_CH_OPCAO10,"
       +" UMO.UMO_CH_OPCAO11,"
       +" UMO.UMO_CH_OPCAO12,"
       +" UMO.UMO_CH_OPCAO13,"
       +" UMO.UMO_CH_OPCAO14,"
       +" UMO.UMO_CH_OPCAO15,"
       +" UMO.UMO_CH_OPCAO16,"
       +" UMO.UMO_CH_OPCAO17,"
       +" UMO.UMO_CH_OPCAO18,"
       +" UMO.UMO_CH_OPCAO19,"
       +" UMO.UMO_CH_OPCAO20,"
       +" UMO.UMO_CH_OPCAO21,"
       +" UMO.UMO_CH_OPCAO22,"
       +" UMO.UMO_CH_OPCAO23,"
       +" UMO.UMO_CH_OPCAO24,"
       +" UMO.UMO_CH_OPCAO25,"
       +" USU.USU_CH_ATIVO,"
       +" USU.USU_CH_ANATOMIA,"
       +" USU.USU_IN_DIASRELATORIO,"
       +" USU.USU_CH_VALOREXTERNO"
       +" FROM LAB_PERFILUSUARIOMODULO PUM,"
       +" LAB_MODULO              MDL,"
       +" LAB_USUARIO             USU,"
       +" LAB_USUARIOMODULO       UMO"
       +" where PUM.MOD_ST_CODIGO = MDL.MOD_ST_CODIGO"
       +" AND UMO.USU_ST_CODIGO = USU.USU_ST_CODIGO"
       +" AND UMO.MOD_ST_CODIGO = MDL.MOD_ST_CODIGO"
       +" AND PUM.PUS_ST_CODIGO = ?"//pusStCodigo '9'
       +" AND USU.USU_ST_CODIGO = ?"//usuStCodigo 'EROS'
       +" order by PUM.PUS_ST_CODIGO, PUM.PUS_IN_SEQUENCIA";



}
